### ISSUE TITLE
Can't get translated country names with 'display' tag

### ISSUE THREAD

**Issue by PieterjanNeskens** [riasvdv/statamic-address-field#8]
Can't seem to get the country in other language like the docs specify.

The display tag outputs 'Belgium' when I expect 'België'

Antlers:
```
{{ address:countries }}
	{{ if alpha2 == locations.0.address.country }}
		{{ display }} 
	{{ /if }}
{{ /address:countries }}
```

.env:
`APP_LOCALE=nl`

**Comment by PieterjanNeskens** [comment]
Never mind, I found the solution because I was working with dates in Statamic.

Needed to set the locale in de Statamic sites config.
From Statamic 5 onwards, needed to create a sites.yaml file in resources folder.

```
default: 
  name: site name
  url: '{{ config:app:url }}'
  locale: nl_BE
```
